### ISSUE TITLE
Error for "raisely deploy"

### ISSUE THREAD

**Issue by jw176** [raisely/cli#24] opened 2022-05-02 01:47 UTC
Hi there,

When I run the command `raisely deploy` I get the following error:
![image](https://user-images.githubusercontent.com/61770531/166174554-8407e7cd-d1f3-49d2-9ae1-ea39a61b47c6.png)

This seems to happen for me across all campaigns.
The folder structure is exactly how it is created from the CLI when running `raisely init` and I have not modified the stylesheets. I am also on windows and using raisely CLI version 1.6.4.

Any help would be much appreciated, thanks.

**Comment by f1yn** [comment] 2022-05-02 02:57
Hey @jw176, I too am on Windows and want to take a look into this.

- Based on your shell, are you using `WSL` for development (and if so, what version of WSL?)
- Otherwise, if you're using powershell or cygwin - let me know 👍🏻 

I can likely go make a fix from the above otherwise I'll prompt you to send over your file structure to Raisely support and we can take a look from there.

**Comment by jw176** [comment] 2022-05-02 03:17
Hi @f1yn thanks for the response.

I don't currently use WSL for development, the prompt is from powershell with some extensions.

**Comment by jw176** [comment] 2022-05-02 08:45
Awesome, thanks

**Comment by f1yn** [comment] 2022-05-04 14:40
**Alright here's the good news:**

I've isolated the failure to a problem with how we're dealing with `win32` path mapping when converting globs and doing file path iteration. There's a few places where the cli is incorrectly using the pattern and fixing it is just a matter of going through each of the files that use this pattern, and switching it to be more cross-platform friendly.

This is honestly likely to do with the fact that most of our team is using `posix` environments, so testing and developing with Windows specific patterns is sometimes easy to forget. So you have my honest apology on that front - we're going to commit to do better going forward.

**The ~bad~ inconvenient news:**

As much as I want to just push a hotfix for this specific function alone, I've found the same pattern used in your trace for multiple parts of the cli. That means an immediate hotfix wont be possible, as there's going to be corrective refactors needed to make sure the same pattern is consistently used in the cli.

**And the somewhat good news:**

To fix this, I've added a todo for myself near the end of the week to fix this bug, but also add in some tests to make sure that path-value mapping is consistent when in `posix` mode (what the current cli is well suited for) and making it also consistent for `win32` mode.

Hopefully, with the platform-specific path tests - we can help ensure that these errors stop happening for Windows users.

@jw176 I'll tag you once this new release is live, but it's likely going to be a few days before this refactor/test suite can be added.

**Comment by jw176** [comment] 2022-05-04 23:52
Thanks for your response @f1yn 

In the meantime, is it possible for me to patch my local version of the CLI so it is compatible with just `win32` path mapping?
I have some large custom components in the backlog and the CLI would definitely be handy.

**Comment by f1yn** [comment] 2022-05-06 06:41
Hey @jw176, while I don't personally recommend it (due to the amount of manual testing needed), you'll probably be able to fix these issues by going through the files below on your local machines and updating them to reflect the `win32` path correctly.

The problem is that while the original failure you've posted is here:
https://github.com/raisely/cli/blob/master/src/actions/campaigns.js#L52-L55

I found the exact same patterns here, so it might be necessary to update the following:
https://github.com/raisely/cli/blob/master/src/actions/components.js#L119-L122
https://github.com/raisely/cli/blob/master/src/actions/components.js#L123-L128

And potentially here: 
https://github.com/raisely/cli/blob/master/src/actions/sync.js
https://github.com/raisely/cli/blob/master/src/deploy.js#L60-L62
https://github.com/raisely/cli/blob/master/src/deploy.js#L77-L80
https://github.com/raisely/cli/blob/master/src/deploy.js#L81-L86

The fact the same problem _could_ be prevalent throughout the package leaves me feeling compelled to put together a better solution & some tests to make sure this does not happen again.

**Comment by f1yn** [comment] 2022-05-08 09:35
Hey @jw176, just letting you know this is fixed in the `1.6.5` release on `npm`.

**Closed by f1yn** 2022-05-08 09:35 UTC

**Comment by jw176** [comment] 2022-05-08 12:51
Awesome! Thanks for your help @f1yn
